[project]
name = "pdf-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nikolai Sandbeck", email = "sandbeck1990@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
pdf-downloader = "pdf_downloader:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
